#! /bin/sh

# find all java source files in src directory
FILES=$(find src -iname "*.java")
FILES1=$(find resource -iname "*")

rm -rf bin
mkdir -p bin

for file in $FILES1
do
    echo "moving file : $file"
	cp $file bin
    
done



# compile each source file into bin directory, exiting on compilation failure
for file in $FILES
do
    echo "compiling $file"
    javac -cp "./src/" -d bin $file
    if [ $? -ne 0 ]
    then
        exit 1
    fi
done



echo "done"
